export enum EngineState {
  UNINITIALIZED = 'UNINITIALIZED',
  INITIALIZED = 'INITIALIZED',
  RUNNING = 'RUNNING',
  LOADING_FILE = 'LOADING_FILE',
  PAUSED = 'PAUSED',
  CANCEL_ALL_SUBROUTINES = 'CANCEL_ALL_SUBROUTINES',
  CANCEL_SUBROUTINE = 'CANCEL_SUBROUTINE',
}
