name: Code Quality Check

permissions:
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  HUSKY: 0
  NX_BASE: main
  NX_HEAD: ${{ github.sha }}

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GAME_ROOT: ${{ secrets.GAME_ROOT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - name: Build
        run: |
          pnpm build

      - run: pnpm exec nx affected --parallel=3 -t lint:ci test typecheck convert knip:ci

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
          retention-days: 3

  sonarqube:
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile --offline

      - name: Load Coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
